using Plots
using LinearAlgebra

import GeneralAttractors.ManifoldUtils: S², fibonacci_sphere, ψx, ψy, ψz
import GeneralAttractors: SphericalDistance
"""
Visulize vector fields on the unit S²⊂ℝ³
generated by rotation around XYZ axes.
"""


scaling = .1


X = fibonacci_sphere(600)
metric = SphericalDistance()

p = [1, 0, 0]
# plt = scatter3d(eachrow(X)...; xlim=[-1.1, 1.1], ylim=[-1.1, 1.1], zlim=[-1.1, 1.1], aspect_ratio=:equal)
plt = scatter3d(xlim=[-1.1, 1.1], ylim=[-1.1, 1.1], zlim=[-1.1, 1.1], aspect_ratio=:equal, size=(800, 800))

for x in eachcol(X)
    d = metric(x, p)
    d > .5 && continue

    for (col, ψ) in zip((:black, :red, :blue), (ψx, ψy, ψz))
        v = ψ(x) .* scaling
        plot!(
            [x[1], x[1]+v[1]],
            [x[2], x[2]+v[2]],
            [x[3], x[3]+v[3]],
            lw=4, color=col, label=nothing
        )
    end

end
scatter!([p[1]], [p[2]], [p[3]], ms=10, color=:red, camera=(90, 0))

v = [-0.0051, -0.0086, 0.0] .* 20
plot!(
    [p[1], p[1]+v[1]],
    [p[2], p[2]+v[2]],
    [p[3], p[3]+v[3]],
    lw=6, color=:black, label=nothing
)
plt